server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 182436
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  redis:
    host: localhost
    password: 123456
    port: 6379

  thymeleaf:
    prefix: classpath:/resources/html/